[workspace]

members = [
    "polar-core",
    "polar-crossgen",
    "polar-c-api",
    "polar-wasm-api",
    "languages/rust/oso",
    "languages/rust/oso-derive",
]

exclude = [
    "docs/examples/quickstart/oso-rust-quickstart"
]

[profile.release]
debug = true

[profile.bench]
debug = true
