baseURL = "https://docs.osohq.com/"
languageCode = "en-us"
title = "Oso Documentation"
theme = ["oso-tailwind", "oso-webpack"]
uglyurls = true

defaultContentLanguage = "any"

# used for Twitter card etc
[params]
  description = "Explore our guides and reference articles for learning Oso and adding it to your application."
  images = ["oso-2020-white-on-black-rounded.png"]

[languages]
  [languages.any]
    weight = -1
    contentDir = "content/any"
    languageName = "Any"

  [languages.java]
    languageName = "Java"
    contentDir = "content/java"
    weight = 1
    [languages.java.params]
      icon = "java"

  [languages.node]
    languageName = "Node.js"
    contentDir = "content/node"
    weight = 2
    [languages.node.params]
      icon = "node-js"

  [languages.python]
    languageName = "Python"
    contentDir = "content/python"
    weight = 3
    [languages.python.params]
      icon = "python"

  [languages.ruby]
    languageName = "Ruby"
    contentDir = "content/ruby"
    weight = 4
    [languages.ruby.params]
      icon = "gem"

  [languages.rust]
    languageName = "Rust"
    contentDir = "content/rust"
    weight = 5
    [languages.rust.params]
      icon = "rust"

  [languages.go]
    languageName = "Go"
    contentDir = "content/go"
    weight = 5
    [languages.go.params]
      icon = "go"

[module]
  [[module.mounts]]
    source = "content/any"
    target = "content"
    lang = "any"

  [[module.mounts]]
    source = "content/any"
    target = "content"
    lang = "java"
  [[module.mounts]]
    source = "content/java"
    target = "content"
    lang = "java"

  [[module.mounts]]
    source = "content/any"
    target = "content"
    lang = "node"
  [[module.mounts]]
    source = "content/node"
    target = "content"
    lang = "node"

  [[module.mounts]]
    source = "content/any"
    target = "content"
    lang = "python"
  [[module.mounts]]
    source = "content/python"
    target = "content"
    lang = "python"

  [[module.mounts]]
    source = "content/any"
    target = "content"
    lang = "ruby"
  [[module.mounts]]
    source = "content/ruby"
    target = "content"
    lang = "ruby"

  [[module.mounts]]
    source = "content/any"
    target = "content"
    lang = "rust"
  [[module.mounts]]
    source = "content/rust"
    target = "content"
    lang = "rust"

  [[module.mounts]]
    source = "content/any"
    target = "content"
    lang = "go"
  [[module.mounts]]
    source = "content/go"
    target = "content"
    lang = "go"

  # Mount the old docs as a subdirectory for now
  [[module.mounts]]
  source = "../docs/_build/html"
  target = "static/v1/"

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = true
      table = true
    [markup.goldmark.renderer]
      unsafe = true
