[package]
name = "oso"
description = "oso is an open source policy engine for authorization thatâ€™s embedded in your application"
authors = ["Oso Security, Inc. <support@osohq.com>"]
license = "Apache-2.0"
homepage = "https://github.com/osohq/oso"
readme = "README.md"

version = "0.8.2"

edition = "2018"

[lib]
bench = false

[[bench]]
name = "bench"
harness = false

[[bin]]
name = "oso"
path = "src/repl.rs"
required-features = ["cli"]

[[example]]
name = "blog"
path = "examples/blog.rs"
required-features = ["anyhow"]

[dependencies]
impl-trait-for-tuples = "0.2"
maplit = "1.0.2"
polar-core = { path = "../../../polar-core", version = "=0.8.2" }
oso-derive = { path = "../oso-derive", version = "=0.8.2", optional = true }
thiserror = "1.0.21"
tracing = { version = "0.1.21", features = ["log"] }
tracing-subscriber = { version = "0.2.13", features = ["fmt"] }

anyhow = { version = "1.0.33", optional = true }
rustyline = { version = "6.3.0", optional = true }
rustyline-derive = { version = "0.3.1", optional = true }
lazy_static = "1.4.0"

uuid = { version = "0.6.5", optional = true }

[dev-dependencies]
anyhow = "1.0.33"
criterion = "0.3.3"
oso-derive = { path = "../oso-derive", version = "=0.8.2" }
tempfile = "3.1.0"
static_assertions = "1.1.0"
uuid = "0.6.5"

[features]
default = ["derive"]
cli = ["rustyline", "rustyline-derive", "anyhow"]
derive = ["oso-derive"]
extra = ["uuid"]
