name: Create SQLAlchemy Integration Release
on:
  push:
    tags:
      - "sqlalchemy-v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  version:
    name: Compute and verify the version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version env
        env:
          github_ref: ${{ github.ref }}
        run: echo "oso_version=${github_ref/refs\/tags\/sqlalchemy-v/}" >> $GITHUB_ENV
      - name: Check python version matches
        run: grep "__version__ = \"$oso_version\"" sqlalchemy_oso/__init__.py
        working-directory: languages/python/sqlalchemy-oso
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: version
    strategy:
      matrix:
        # Q: Is there any benefit to building on multiple platforms?
        os: [ubuntu-latest]
    env:
      # Skip Python 2.7 and Python 3.5
      CIBW_SKIP: "cp27-* cp35-* pp27-*"
      # 64-bit builds only
      CIBW_BUILD: "*64"
      # Used in build.py to find right files
      CIBW_ENVIRONMENT: OSO_ENV=CI TOX_PARALLEL_NO_SPINNER=1

      CIBW_TEST_REQUIRES: tox
      CIBW_TEST_COMMAND: tox -p -c {project}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.7"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.4.2
      - name: Copy in readme
        run: |
          rm languages/python/sqlalchemy-oso/README.md
          cp README.md languages/python/sqlalchemy-oso/README.md
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        working-directory: languages/python/sqlalchemy-oso
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: languages/python/sqlalchemy-oso/wheelhouse/*.whl

  # TODO what validation can we do here.
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      [
        build_wheels,
      ]
    steps:
      - name: Set version output
        id: version
        env:
          github_ref: ${{ github.ref }}
        run: echo "::set-output name=oso_version::${github_ref/refs\/tags\/sqlalchemy-v/}"
      - name: Download oso python wheels from package run
        uses: actions/download-artifact@v1
        with:
          name: wheel
      - name: Zip file
        run: zip --junk-paths -r sqlalchemy-oso-python.zip wheel/
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: sqlalchemy-v${{ steps.version.outputs.oso_version }}
          release_name: sqlalchemy-oso ${{ steps.version.outputs.oso_version }}
          body: |
            sqlalchemy-oso ${{ steps.version.outputs.oso_version }}
          draft: false
          prerelease: true
      - name: Upload Python Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./sqlalchemy-oso-python.zip
          asset_name: sqlalchemy-oso-python-${{ steps.version.outputs.oso_version }}.zip
          asset_content_type: application/zip
